version: 2
project_name: blu

builds:
  - id: blu
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/Get-Blu/blu-code/internal/version.Version={{.Version}}
    main: ./main.go
    binary: blu

archives:
  - id: default
    builds:
      - blu
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- if eq .Os "darwin" }}mac-
      {{- else if eq .Os "windows" }}windows-
      {{- else if eq .Os "linux" }}linux-{{end}}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip

  - id: binary
    builds:
      - blu
    formats:
      - binary
    name_template: >-
      {{ .ProjectName }}-
      {{- if eq .Os "darwin" }}darwin-
      {{- else if eq .Os "windows" }}windows-
      {{- else if eq .Os "linux" }}linux-{{end}}
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Version }}-{{ .Timestamp }}"

# This is the key fix: Allow GoReleaser to overwrite existing releases/assets
release:
  github:
    owner: Get-Blu
    name: blu-code
  replace: true
  make_latest: true

nfpms:
  - builds:
      - blu
    maintainer: Garv Agnihotri <garvagnihotri22@gmail.com>
    description: Terminal-based AI assistant for software development
    homepage: "https://github.com/Get-Blu/blu-code"
    license: MIT
    formats:
      - deb
      - rpm
    file_name_template: >-
      {{ .ProjectName }}-
      {{- if eq .Os "darwin" }}mac
      {{- else }}{{ .Os }}{{ end }}-{{ .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^doc:"
      - "^test:"
      - "^ci:"
      - "^ignore:"
      - "^example:"
      - "^wip:"