package models

const (
	ProviderOpenAI ModelProvider = "openai"

	GPT41        ModelID = "gpt-4.1"
	GPT41Mini    ModelID = "gpt-4.1-mini"
	GPT41Nano    ModelID = "gpt-4.1-nano"
	GPT45Preview ModelID = "gpt-4.5-preview"
	GPT46        ModelID = "gpt-4.6"
	GPT46Mini    ModelID = "gpt-4.6-mini"
	GPT5         ModelID = "gpt-5"
	GPT5Mini     ModelID = "gpt-5-mini"
	GPT5Turbo    ModelID = "gpt-5-turbo"
	GPT4o        ModelID = "gpt-4o"
	GPT4oMini    ModelID = "gpt-4o-mini"
	O1           ModelID = "o1"
	O1Pro        ModelID = "o1-pro"
	O1Mini       ModelID = "o1-mini"
	O3           ModelID = "o3"
	O3Mini       ModelID = "o3-mini"
	O3Ultra      ModelID = "o3-ultra"
	O4Mini       ModelID = "o4-mini"
	GPT5_2       ModelID = "gpt-5.2"
	GPT5_3Codex  ModelID = "gpt-5.3-codex"
	GPTOSS120B   ModelID = "gpt-oss-120b"
	GPTOSS20B    ModelID = "gpt-oss-20b"
)

var OpenAIModels = map[ModelID]Model{
	GPT41: {
		ID:                  GPT41,
		Name:                "GPT 4.1",
		Provider:            ProviderOpenAI,
		APIModel:            "gpt-4.1",
		CostPer1MIn:         2.00,
		CostPer1MInCached:   0.50,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        8.00,
		ContextWindow:       1_047_576,
		DefaultMaxTokens:    20000,
		SupportsAttachments: true,
	},
	GPT41Mini: {
		ID:                  GPT41Mini,
		Name:                "GPT 4.1 mini",
		Provider:            ProviderOpenAI,
		APIModel:            "gpt-4.1",
		CostPer1MIn:         0.40,
		CostPer1MInCached:   0.10,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        1.60,
		ContextWindow:       200_000,
		DefaultMaxTokens:    20000,
		SupportsAttachments: true,
	},
	GPT41Nano: {
		ID:                  GPT41Nano,
		Name:                "GPT 4.1 nano",
		Provider:            ProviderOpenAI,
		APIModel:            "gpt-4.1-nano",
		CostPer1MIn:         0.10,
		CostPer1MInCached:   0.025,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        0.40,
		ContextWindow:       1_047_576,
		DefaultMaxTokens:    20000,
		SupportsAttachments: true,
	},
	GPT45Preview: {
		ID:                  GPT45Preview,
		Name:                "GPT 4.5 preview",
		Provider:            ProviderOpenAI,
		APIModel:            "gpt-4.5-preview",
		CostPer1MIn:         75.00,
		CostPer1MInCached:   37.50,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        150.00,
		ContextWindow:       128_000,
		DefaultMaxTokens:    15000,
		SupportsAttachments: true,
	},
	GPT4o: {
		ID:                  GPT4o,
		Name:                "GPT 4o",
		Provider:            ProviderOpenAI,
		APIModel:            "gpt-4o",
		CostPer1MIn:         2.50,
		CostPer1MInCached:   1.25,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        10.00,
		ContextWindow:       128_000,
		DefaultMaxTokens:    4096,
		SupportsAttachments: true,
	},
	GPT4oMini: {
		ID:                  GPT4oMini,
		Name:                "GPT 4o mini",
		Provider:            ProviderOpenAI,
		APIModel:            "gpt-4o-mini",
		CostPer1MIn:         0.15,
		CostPer1MInCached:   0.075,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        0.60,
		ContextWindow:       128_000,
		SupportsAttachments: true,
	},
	O1: {
		ID:                  O1,
		Name:                "O1",
		Provider:            ProviderOpenAI,
		APIModel:            "o1",
		CostPer1MIn:         15.00,
		CostPer1MInCached:   7.50,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        60.00,
		ContextWindow:       200_000,
		DefaultMaxTokens:    50000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	O1Pro: {
		ID:                  O1Pro,
		Name:                "o1 pro",
		Provider:            ProviderOpenAI,
		APIModel:            "o1-pro",
		CostPer1MIn:         150.00,
		CostPer1MInCached:   0.0,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        600.00,
		ContextWindow:       200_000,
		DefaultMaxTokens:    50000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	O1Mini: {
		ID:                  O1Mini,
		Name:                "o1 mini",
		Provider:            ProviderOpenAI,
		APIModel:            "o1-mini",
		CostPer1MIn:         1.10,
		CostPer1MInCached:   0.55,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        4.40,
		ContextWindow:       128_000,
		DefaultMaxTokens:    50000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	O3: {
		ID:                  O3,
		Name:                "o3",
		Provider:            ProviderOpenAI,
		APIModel:            "o3",
		CostPer1MIn:         10.00,
		CostPer1MInCached:   2.50,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        40.00,
		ContextWindow:       200_000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	O3Mini: {
		ID:                  O3Mini,
		Name:                "o3 mini",
		Provider:            ProviderOpenAI,
		APIModel:            "o3-mini",
		CostPer1MIn:         1.10,
		CostPer1MInCached:   0.55,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        4.40,
		ContextWindow:       200_000,
		DefaultMaxTokens:    50000,
		CanReason:           true,
		SupportsAttachments: false,
	},
	O4Mini: {
		ID:                  O4Mini,
		Name:                "o4 mini",
		Provider:            ProviderOpenAI,
		APIModel:            "o4-mini",
		CostPer1MIn:         1.10,
		CostPer1MInCached:   0.275,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        4.40,
		ContextWindow:       128_000,
		DefaultMaxTokens:    50000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	GPT46: {
		ID:                  GPT46,
		Name:                "GPT 4.6",
		Provider:            ProviderOpenAI,
		APIModel:            "gpt-4.6",
		CostPer1MIn:         2.00,
		CostPer1MInCached:   0.50,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        8.00,
		ContextWindow:       2_000_000,
		DefaultMaxTokens:    128000,
		SupportsAttachments: true,
	},
	GPT5: {
		ID:                  GPT5,
		Name:                "GPT 5",
		Provider:            ProviderOpenAI,
		APIModel:            "gpt-5",
		CostPer1MIn:         10.00,
		CostPer1MInCached:   5.00,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        30.00,
		ContextWindow:       2_000_000,
		DefaultMaxTokens:    128000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	GPT5Turbo: {
		ID:                  GPT5Turbo,
		Name:                "GPT 5 Turbo",
		Provider:            ProviderOpenAI,
		APIModel:            "gpt-5-turbo",
		CostPer1MIn:         2.00,
		CostPer1MInCached:   1.00,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        8.00,
		ContextWindow:       1_000_000,
		DefaultMaxTokens:    128000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	O3Ultra: {
		ID:                  O3Ultra,
		Name:                "o3 ultra",
		Provider:            ProviderOpenAI,
		APIModel:            "o3-ultra",
		CostPer1MIn:         15.00,
		CostPer1MInCached:   7.50,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        60.00,
		ContextWindow:       200_000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	GPT5_2: {
		ID:                  GPT5_2,
		Name:                "GPT 5.2",
		Provider:            ProviderOpenAI,
		APIModel:            "gpt-5.2",
		CostPer1MIn:         8.00,
		CostPer1MInCached:   4.00,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        24.00,
		ContextWindow:       400_000,
		DefaultMaxTokens:    128_000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	GPT5_3Codex: {
		ID:                  GPT5_3Codex,
		Name:                "GPT 5.3 Codex",
		Provider:            ProviderOpenAI,
		APIModel:            "gpt-5.3-codex",
		CostPer1MIn:         6.00,
		CostPer1MInCached:   3.00,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        18.00,
		ContextWindow:       500_000,
		DefaultMaxTokens:    128_000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	GPTOSS120B: {
		ID:                  GPTOSS120B,
		Name:                "GPT OSS 120B",
		Provider:            ProviderOpenAI,
		APIModel:            "gpt-oss-120b",
		CostPer1MIn:         0.50,
		CostPer1MInCached:   0.25,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        1.50,
		ContextWindow:       128_000,
		DefaultMaxTokens:    32_000,
		SupportsAttachments: true,
	},
	GPTOSS20B: {
		ID:                  GPTOSS20B,
		Name:                "GPT OSS 20B",
		Provider:            ProviderOpenAI,
		APIModel:            "gpt-oss-20b",
		CostPer1MIn:         0.10,
		CostPer1MInCached:   0.05,
		CostPer1MOutCached:  0.0,
		CostPer1MOut:        0.30,
		ContextWindow:       128_000,
		DefaultMaxTokens:    32_000,
		SupportsAttachments: true,
	},
}
